language: php

php:
    - 5.2
    - 5.3.2
    - 5.3
    - 5.4

branches:
    only: master

notifications:
    email: false
    irc: "irc.iiens.net#Erebot"

before_script:
    - git submodule update --init
    - (php -m | grep intl &> /dev/null) || wget http://pecl.php.net/get/intl-1.1.2.tgz
    - (php -m | grep intl &> /dev/null) || tar -xzf intl-1.1.2.tgz
    - (php -m | grep intl &> /dev/null) || sh -c "cd intl-1.1.2 && phpize && ./configure --enable-intl && make && sudo make install"
    - (php -m | grep intl &> /dev/null) || echo "extension_dir=`php-config --extension-dir`" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
    - (php -m | grep intl &> /dev/null) || echo "extension=intl.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
    - php --re intl

script: phpunit --bootstrap tests/testenv/bootstrap.php tests/

