language: php
dist: trusty

sudo: false

cache:
    directories:
    - vendor
    - $HOME/.composer/cache

php:
    - 7.0
    - 7.1
    - 7.2
    - nightly

notifications:
    email: false
    irc:
      channels:
        - "irc.iiens.net#Erebot"
      on_success: change
      on_failure: always

before_script:
    - rm composer.lock
    - composer self-update -n
    - composer install -n

script:
    - bin/wordlist-converter tests/wordlists/count.txt
    - vendor/bin/phpunit --coverage-clover clover.xml
    - vendor/bin/phpcs

after_script:
    - vendor/bin/update-docs.sh

after_success:
    - composer require --dev satooshi/php-coveralls
    - travis_retry vendor/bin/php-coveralls -n -v

