language: php

php:
    - 5.3.3
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

notifications:
    email: false
    irc: "irc.iiens.net#Erebot"

before_script:
    - (php -m | grep intl &> /dev/null) || pecl install pecl/intl
    - composer self-update -n
    - composer install --dev -n

script:
    - php bin/wordlist-converter tests/wordlists/count.txt
    - phpunit --coverage-clover clover.xml --bootstrap vendor/erebot/testenv/bootstrap.php tests/

after_script:
    - composer require --dev $prefer_source "satooshi/php-coveralls dev-master"
    - php vendor/bin/coveralls -n -v

