language: php

php:
    - 5.2
    - 5.3.2
    - 5.3
    - 5.4

branches:
    only: master

notifications:
    email: false
    irc: "irc.iiens.net#Erebot"

before_script:
    - git submodule update --init

script: phpunit --bootstrap tests/testenv/bootstrap.php tests/

